# https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run
firebase:
  bucket: <your-project-id>.appspot.com
  results-bucket: test_results
  record-video: false
  project: your-project-id

  # Paths to app and test apk and test result output directory
  app: /path/to/app/apk
  test: /path/to/test/apk
  output: ./test_result

  # Path to service account key txt
  service-key: /path/to/service/key.txt
  
  device:
      model: NexusLowRes
      version: '28'